version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: collectief
  MYSQL_USER: collectief_user
  MYSQL_PASSWORD: collectief_user

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "3307:3307"
    expose:
      - 3307
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: "OuPfme45oAM#$6m6S8lqy4P!%QffaxlYFlCnmP45zyaloZ5Zw="
      MYSQL_HOST: localhost
      MYSQL_TCP_PORT: 3307
    command: --sql-mode=""
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    restart: always
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "3002:3002"
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client   
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3003:3000"